"""Generate a PostgreSQL schema and seed script for pgAdmin."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT_PATH = Path(__file__).resolve().parent.parent
CITY_JSON_PATH = ROOT_PATH / "data" / "city.json"
POSTGRES_SQL_PATH = ROOT_PATH / "data" / "city_postgres.sql"
SCHEMA_NAME = "city_simulator"


DROP_TABLES = (
    "incompatibility_measures",
    "incompatibilities",
    "synergy_effects",
    "synergy_measures",
    "synergies",
    "measure_effects",
    "measures",
    "district_indicators",
    "districts",
    "weights",
    "indicators",
    "reference_scenarios",
    "scoring",
    "rules",
    "metadata",
)


def generate_postgres_sql(
    json_path: Path = CITY_JSON_PATH,
    schema_name: str = SCHEMA_NAME,
) -> str:
    """Return a PostgreSQL script that creates and seeds the city dataset."""
    with json_path.open(encoding="utf-8") as source:
        city = json.load(source)

    statements = [
        "-- Generated from data/city.json.",
        "-- Run this in pgAdmin Query Tool inside your target database.",
        f"CREATE SCHEMA IF NOT EXISTS {quote_identifier(schema_name)};",
        f"SET search_path TO {quote_identifier(schema_name)};",
        "BEGIN;",
    ]
    statements.extend(
        f"DROP TABLE IF EXISTS {quote_identifier(table)} CASCADE;"
        for table in DROP_TABLES
    )
    statements.extend(_schema_statements())
    statements.extend(_seed_statements(city))
    statements.extend(
        [
            "COMMIT;",
            "",
            f"SET search_path TO {quote_identifier(schema_name)};",
            "SELECT 'districts' AS table_name, COUNT(*) FROM districts",
            "UNION ALL SELECT 'indicators', COUNT(*) FROM indicators",
            "UNION ALL SELECT 'measures', COUNT(*) FROM measures",
            "UNION ALL SELECT 'measure_effects', COUNT(*) FROM measure_effects",
            "UNION ALL SELECT 'synergies', COUNT(*) FROM synergies",
            "UNION ALL SELECT 'incompatibilities', COUNT(*) FROM incompatibilities;",
            "",
        ]
    )
    return "\n".join(statements)


def quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def quote_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def json_literal(value: Any) -> str:
    return quote_literal(json.dumps(value, ensure_ascii=False, separators=(",", ":"))) + "::jsonb"


def number_literal(value: Any) -> str:
    return "NULL" if value is None else str(value)


def _schema_statements() -> list[str]:
    return [
        """
CREATE TABLE metadata (
    key TEXT PRIMARY KEY,
    value_json JSONB NOT NULL
);
""".strip(),
        """
CREATE TABLE rules (
    key TEXT PRIMARY KEY,
    value_json JSONB NOT NULL
);
""".strip(),
        """
CREATE TABLE scoring (
    key TEXT PRIMARY KEY,
    value_json JSONB NOT NULL
);
""".strip(),
        """
CREATE TABLE reference_scenarios (
    name TEXT PRIMARY KEY,
    data_json JSONB NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
""".strip(),
        """
CREATE TABLE indicators (
    id TEXT PRIMARY KEY,
    direction TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
""".strip(),
        """
CREATE TABLE weights (
    indicator_id TEXT PRIMARY KEY REFERENCES indicators(id) ON DELETE CASCADE,
    weight NUMERIC NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
""".strip(),
        """
CREATE TABLE districts (
    name TEXT PRIMARY KEY,
    population_share NUMERIC NOT NULL,
    reference_d NUMERIC,
    profile TEXT NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
""".strip(),
        """
CREATE TABLE district_indicators (
    district_name TEXT NOT NULL REFERENCES districts(name) ON DELETE CASCADE,
    indicator_id TEXT NOT NULL REFERENCES indicators(id) ON DELETE CASCADE,
    value NUMERIC NOT NULL,
    PRIMARY KEY (district_name, indicator_id)
);
""".strip(),
        """
CREATE TABLE measures (
    id TEXT PRIMARY KEY,
    direction TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('city', 'district')),
    cost INTEGER NOT NULL,
    lag INTEGER NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
""".strip(),
        """
CREATE TABLE measure_effects (
    measure_id TEXT NOT NULL REFERENCES measures(id) ON DELETE CASCADE,
    indicator_id TEXT NOT NULL REFERENCES indicators(id) ON DELETE CASCADE,
    effect NUMERIC NOT NULL,
    PRIMARY KEY (measure_id, indicator_id)
);
""".strip(),
        """
CREATE TABLE synergies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_measure TEXT NOT NULL REFERENCES measures(id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL UNIQUE
);
""".strip(),
        """
CREATE TABLE synergy_measures (
    synergy_id INTEGER NOT NULL REFERENCES synergies(id) ON DELETE CASCADE,
    measure_id TEXT NOT NULL REFERENCES measures(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    PRIMARY KEY (synergy_id, position)
);
""".strip(),
        """
CREATE TABLE synergy_effects (
    synergy_id INTEGER NOT NULL REFERENCES synergies(id) ON DELETE CASCADE,
    indicator_id TEXT NOT NULL REFERENCES indicators(id) ON DELETE CASCADE,
    effect NUMERIC NOT NULL,
    PRIMARY KEY (synergy_id, indicator_id)
);
""".strip(),
        """
CREATE TABLE incompatibilities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope TEXT NOT NULL CHECK (scope IN ('global', 'same_district')),
    reason TEXT NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
""".strip(),
        """
CREATE TABLE incompatibility_measures (
    incompatibility_id INTEGER NOT NULL REFERENCES incompatibilities(id) ON DELETE CASCADE,
    measure_id TEXT NOT NULL REFERENCES measures(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    PRIMARY KEY (incompatibility_id, position)
);
""".strip(),
    ]


def _seed_statements(city: dict) -> list[str]:
    statements = []
    statements.extend(
        _insert_key_values(
            "metadata",
            {
                "budget": city["budget"],
                "horizon": city["horizon"],
                "horizon_unit": city["horizon_unit"],
            },
        )
    )
    statements.extend(_insert_key_values("rules", city["rules"]))
    statements.extend(_insert_key_values("scoring", city["scoring"]))

    for order, (indicator_id, indicator) in enumerate(city["indicators"].items()):
        statements.append(
            "INSERT INTO indicators (id, direction, name, description, order_index) "
            f"VALUES ({quote_literal(indicator_id)}, {quote_literal(indicator['direction'])}, "
            f"{quote_literal(indicator['name'])}, {quote_literal(indicator['description'])}, {order});"
        )

    for order, (indicator_id, weight) in enumerate(city["weights"].items()):
        statements.append(
            "INSERT INTO weights (indicator_id, weight, order_index) "
            f"VALUES ({quote_literal(indicator_id)}, {number_literal(weight)}, {order});"
        )

    for order, (district_name, district) in enumerate(city["districts"].items()):
        statements.append(
            "INSERT INTO districts (name, population_share, reference_d, profile, order_index) "
            f"VALUES ({quote_literal(district_name)}, {number_literal(district['population_share'])}, "
            f"{number_literal(district.get('reference_D'))}, {quote_literal(district['profile'])}, {order});"
        )
        for indicator_id, value in district["indicators"].items():
            statements.append(
                "INSERT INTO district_indicators (district_name, indicator_id, value) "
                f"VALUES ({quote_literal(district_name)}, {quote_literal(indicator_id)}, {number_literal(value)});"
            )

    for order, measure in enumerate(city["measures"]):
        statements.append(
            "INSERT INTO measures (id, direction, name, type, cost, lag, order_index) "
            f"VALUES ({quote_literal(measure['id'])}, {quote_literal(measure['direction'])}, "
            f"{quote_literal(measure['name'])}, {quote_literal(measure['type'])}, "
            f"{number_literal(measure['cost'])}, {number_literal(measure['lag'])}, {order});"
        )
        for indicator_id, effect in measure["effects"].items():
            statements.append(
                "INSERT INTO measure_effects (measure_id, indicator_id, effect) "
                f"VALUES ({quote_literal(measure['id'])}, {quote_literal(indicator_id)}, {number_literal(effect)});"
            )

    for order, synergy in enumerate(city["synergies"], start=1):
        statements.append(
            "INSERT INTO synergies (id, target_measure, order_index) "
            f"VALUES ({order}, {quote_literal(synergy['target_measure'])}, {order - 1});"
        )
        for position, measure_id in enumerate(synergy["measures"]):
            statements.append(
                "INSERT INTO synergy_measures (synergy_id, measure_id, position) "
                f"VALUES ({order}, {quote_literal(measure_id)}, {position});"
            )
        for indicator_id, effect in synergy["effects"].items():
            statements.append(
                "INSERT INTO synergy_effects (synergy_id, indicator_id, effect) "
                f"VALUES ({order}, {quote_literal(indicator_id)}, {number_literal(effect)});"
            )

    for order, conflict in enumerate(city["incompatibilities"], start=1):
        statements.append(
            "INSERT INTO incompatibilities (id, scope, reason, order_index) "
            f"VALUES ({order}, {quote_literal(conflict['scope'])}, "
            f"{quote_literal(conflict['reason'])}, {order - 1});"
        )
        for position, measure_id in enumerate(conflict["measures"]):
            statements.append(
                "INSERT INTO incompatibility_measures (incompatibility_id, measure_id, position) "
                f"VALUES ({order}, {quote_literal(measure_id)}, {position});"
            )

    for order, (name, data) in enumerate(city["reference_scenarios"].items()):
        statements.append(
            "INSERT INTO reference_scenarios (name, data_json, order_index) "
            f"VALUES ({quote_literal(name)}, {json_literal(data)}, {order});"
        )

    return statements


def _insert_key_values(table: str, values: dict[str, Any]) -> list[str]:
    return [
        f"INSERT INTO {quote_identifier(table)} (key, value_json) VALUES "
        f"({quote_literal(key)}, {json_literal(value)});"
        for key, value in values.items()
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a PostgreSQL seed script.")
    parser.add_argument("--json", type=Path, default=CITY_JSON_PATH)
    parser.add_argument("--out", type=Path, default=POSTGRES_SQL_PATH)
    parser.add_argument("--schema", default=SCHEMA_NAME)
    args = parser.parse_args(argv)

    sql = generate_postgres_sql(args.json, args.schema)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(sql, encoding="utf-8")
    print(f"PostgreSQL script created: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
