-- Generated from data/city.json.
-- Run this in pgAdmin Query Tool inside your target database.
CREATE SCHEMA IF NOT EXISTS "city_simulator";
SET search_path TO "city_simulator";
BEGIN;
DROP TABLE IF EXISTS "incompatibility_measures" CASCADE;
DROP TABLE IF EXISTS "incompatibilities" CASCADE;
DROP TABLE IF EXISTS "synergy_effects" CASCADE;
DROP TABLE IF EXISTS "synergy_measures" CASCADE;
DROP TABLE IF EXISTS "synergies" CASCADE;
DROP TABLE IF EXISTS "measure_effects" CASCADE;
DROP TABLE IF EXISTS "measures" CASCADE;
DROP TABLE IF EXISTS "district_indicators" CASCADE;
DROP TABLE IF EXISTS "districts" CASCADE;
DROP TABLE IF EXISTS "weights" CASCADE;
DROP TABLE IF EXISTS "indicators" CASCADE;
DROP TABLE IF EXISTS "reference_scenarios" CASCADE;
DROP TABLE IF EXISTS "scoring" CASCADE;
DROP TABLE IF EXISTS "rules" CASCADE;
DROP TABLE IF EXISTS "metadata" CASCADE;
CREATE TABLE metadata (
    key TEXT PRIMARY KEY,
    value_json JSONB NOT NULL
);
CREATE TABLE rules (
    key TEXT PRIMARY KEY,
    value_json JSONB NOT NULL
);
CREATE TABLE scoring (
    key TEXT PRIMARY KEY,
    value_json JSONB NOT NULL
);
CREATE TABLE reference_scenarios (
    name TEXT PRIMARY KEY,
    data_json JSONB NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
CREATE TABLE indicators (
    id TEXT PRIMARY KEY,
    direction TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
CREATE TABLE weights (
    indicator_id TEXT PRIMARY KEY REFERENCES indicators(id) ON DELETE CASCADE,
    weight NUMERIC NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
CREATE TABLE districts (
    name TEXT PRIMARY KEY,
    population_share NUMERIC NOT NULL,
    reference_d NUMERIC,
    profile TEXT NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
CREATE TABLE district_indicators (
    district_name TEXT NOT NULL REFERENCES districts(name) ON DELETE CASCADE,
    indicator_id TEXT NOT NULL REFERENCES indicators(id) ON DELETE CASCADE,
    value NUMERIC NOT NULL,
    PRIMARY KEY (district_name, indicator_id)
);
CREATE TABLE measures (
    id TEXT PRIMARY KEY,
    direction TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('city', 'district')),
    cost INTEGER NOT NULL,
    lag INTEGER NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
CREATE TABLE measure_effects (
    measure_id TEXT NOT NULL REFERENCES measures(id) ON DELETE CASCADE,
    indicator_id TEXT NOT NULL REFERENCES indicators(id) ON DELETE CASCADE,
    effect NUMERIC NOT NULL,
    PRIMARY KEY (measure_id, indicator_id)
);
CREATE TABLE synergies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_measure TEXT NOT NULL REFERENCES measures(id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL UNIQUE
);
CREATE TABLE synergy_measures (
    synergy_id INTEGER NOT NULL REFERENCES synergies(id) ON DELETE CASCADE,
    measure_id TEXT NOT NULL REFERENCES measures(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    PRIMARY KEY (synergy_id, position)
);
CREATE TABLE synergy_effects (
    synergy_id INTEGER NOT NULL REFERENCES synergies(id) ON DELETE CASCADE,
    indicator_id TEXT NOT NULL REFERENCES indicators(id) ON DELETE CASCADE,
    effect NUMERIC NOT NULL,
    PRIMARY KEY (synergy_id, indicator_id)
);
CREATE TABLE incompatibilities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope TEXT NOT NULL CHECK (scope IN ('global', 'same_district')),
    reason TEXT NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
CREATE TABLE incompatibility_measures (
    incompatibility_id INTEGER NOT NULL REFERENCES incompatibilities(id) ON DELETE CASCADE,
    measure_id TEXT NOT NULL REFERENCES measures(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    PRIMARY KEY (incompatibility_id, position)
);
INSERT INTO "metadata" (key, value_json) VALUES ('budget', '100'::jsonb);
INSERT INTO "metadata" (key, value_json) VALUES ('horizon', '8'::jsonb);
INSERT INTO "metadata" (key, value_json) VALUES ('horizon_unit', '"квартал"'::jsonb);
INSERT INTO "rules" (key, value_json) VALUES ('decision_count', '5'::jsonb);
INSERT INTO "rules" (key, value_json) VALUES ('max_per_direction', '2'::jsonb);
INSERT INTO "rules" (key, value_json) VALUES ('allow_repeats', 'false'::jsonb);
INSERT INTO "rules" (key, value_json) VALUES ('unspent_budget_bonus', '0'::jsonb);
INSERT INTO "scoring" (key, value_json) VALUES ('minimum', '0'::jsonb);
INSERT INTO "scoring" (key, value_json) VALUES ('maximum', '100'::jsonb);
INSERT INTO "scoring" (key, value_json) VALUES ('higher_is_better', 'true'::jsonb);
INSERT INTO "scoring" (key, value_json) VALUES ('critical_threshold', '40'::jsonb);
INSERT INTO "scoring" (key, value_json) VALUES ('average_weight', '0.7'::jsonb);
INSERT INTO "scoring" (key, value_json) VALUES ('minimum_weight', '0.3'::jsonb);
INSERT INTO "scoring" (key, value_json) VALUES ('critical_penalty', '1.0'::jsonb);
INSERT INTO indicators (id, direction, name, description, order_index) VALUES ('T1', 'Транспорт', 'Разгрузка дорог', '100 = нет пробок в час пик, 0 = стоит всё', 0);
INSERT INTO indicators (id, direction, name, description, order_index) VALUES ('T2', 'Транспорт', 'Доступность общественного транспорта', '100 = все жители в 500 м от остановки с интервалом ≤10 мин', 1);
INSERT INTO indicators (id, direction, name, description, order_index) VALUES ('E1', 'Экология', 'Озеленение', '100 = ≥20 м² зелени на жителя', 2);
INSERT INTO indicators (id, direction, name, description, order_index) VALUES ('E2', 'Экология', 'Качество воздуха', '100 = зимой AQI ≤50, 0 = хронический смог', 3);
INSERT INTO indicators (id, direction, name, description, order_index) VALUES ('S1', 'Соцсфера', 'Школы и детсады', '100 = 100% нормативной потребности, без 2-й смены', 4);
INSERT INTO indicators (id, direction, name, description, order_index) VALUES ('S2', 'Соцсфера', 'Поликлиники и первичная медпомощь', '100 = норматив на жителя выполнен полностью', 5);
INSERT INTO indicators (id, direction, name, description, order_index) VALUES ('B1', 'Безопасность', 'Безопасность улиц', '100 = освещение и камеры везде, минимум происшествий', 6);
INSERT INTO indicators (id, direction, name, description, order_index) VALUES ('B2', 'Безопасность', 'Безопасность дорожного движения', '100 = минимум ДТП с пострадавшими', 7);
INSERT INTO indicators (id, direction, name, description, order_index) VALUES ('C1', 'Сервисы', 'Надёжность ЖКХ', '100 = нет аварий отопления/воды за год', 8);
INSERT INTO indicators (id, direction, name, description, order_index) VALUES ('C2', 'Сервисы', 'Скорость решения обращений жителей', '100 = все обращения закрыты в срок', 9);
INSERT INTO weights (indicator_id, weight, order_index) VALUES ('T1', 0.1, 0);
INSERT INTO weights (indicator_id, weight, order_index) VALUES ('T2', 0.1, 1);
INSERT INTO weights (indicator_id, weight, order_index) VALUES ('E1', 0.09, 2);
INSERT INTO weights (indicator_id, weight, order_index) VALUES ('E2', 0.11, 3);
INSERT INTO weights (indicator_id, weight, order_index) VALUES ('S1', 0.11, 4);
INSERT INTO weights (indicator_id, weight, order_index) VALUES ('S2', 0.11, 5);
INSERT INTO weights (indicator_id, weight, order_index) VALUES ('B1', 0.09, 6);
INSERT INTO weights (indicator_id, weight, order_index) VALUES ('B2', 0.09, 7);
INSERT INTO weights (indicator_id, weight, order_index) VALUES ('C1', 0.1, 8);
INSERT INTO weights (indicator_id, weight, order_index) VALUES ('C2', 0.1, 9);
INSERT INTO districts (name, population_share, reference_d, profile, order_index) VALUES ('Есиль', 0.27, 62.99, 'Богатый, но с пробками на мостах и переполненными школами.', 0);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Есиль', 'T1', 45);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Есиль', 'T2', 62);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Есиль', 'E1', 68);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Есиль', 'E2', 72);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Есиль', 'S1', 48);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Есиль', 'S2', 55);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Есиль', 'B1', 78);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Есиль', 'B2', 60);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Есиль', 'C1', 75);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Есиль', 'C2', 70);
INSERT INTO districts (name, population_share, reference_d, profile, order_index) VALUES ('Алматы', 0.24, 57.06, 'Старый ЖКХ и пробки.', 1);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Алматы', 'T1', 40);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Алматы', 'T2', 75);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Алматы', 'E1', 50);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Алматы', 'E2', 55);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Алматы', 'S1', 60);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Алматы', 'S2', 65);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Алматы', 'B1', 62);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Алматы', 'B2', 52);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Алматы', 'C1', 50);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Алматы', 'C2', 60);
INSERT INTO districts (name, population_share, reference_d, profile, order_index) VALUES ('Сарыарка', 0.2, 54.65, 'Смог от частного сектора, слабое озеленение.', 2);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Сарыарка', 'T1', 50);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Сарыарка', 'T2', 70);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Сарыарка', 'E1', 42);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Сарыарка', 'E2', 40);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Сарыарка', 'S1', 62);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Сарыарка', 'S2', 68);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Сарыарка', 'B1', 58);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Сарыарка', 'B2', 55);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Сарыарка', 'C1', 45);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Сарыарка', 'C2', 55);
INSERT INTO districts (name, population_share, reference_d, profile, order_index) VALUES ('Байконур', 0.13, 56.63, 'Середняк без ярких перекосов.', 3);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Байконур', 'T1', 52);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Байконур', 'T2', 68);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Байконур', 'E1', 55);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Байконур', 'E2', 50);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Байконур', 'S1', 58);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Байконур', 'S2', 60);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Байконур', 'B1', 52);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Байконур', 'B2', 58);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Байконур', 'C1', 55);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Байконур', 'C2', 58);
INSERT INTO districts (name, population_share, reference_d, profile, order_index) VALUES ('Нура', 0.16, 49.18, 'Главный «аутсайдер» по соцсфере и транспорту.', 4);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Нура', 'T1', 55);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Нура', 'T2', 40);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Нура', 'E1', 45);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Нура', 'E2', 65);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Нура', 'S1', 38);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Нура', 'S2', 35);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Нура', 'B1', 55);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Нура', 'B2', 50);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Нура', 'C1', 60);
INSERT INTO district_indicators (district_name, indicator_id, value) VALUES ('Нура', 'C2', 50);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M1', 'Транспорт', 'Выделенные полосы для автобусов', 'district', 18, 2, 0);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M1', 'T1', 6);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M1', 'T2', 9);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M2', 'Транспорт', 'Умные светофоры (адаптивное управление)', 'city', 22, 2, 1);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M2', 'T1', 4);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M2', 'B2', 3);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M3', 'Транспорт', 'Линия ЛРТ / расширение', 'district', 30, 4, 2);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M3', 'T1', 16);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M3', 'T2', 20);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M3', 'E2', 4);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M4', 'Экология', 'Парк / сквер', 'district', 15, 2, 3);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M4', 'E1', 12);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M4', 'E2', 3);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M4', 'B1', 2);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M5', 'Экология', 'Перевод частного сектора на чистое топливо', 'district', 25, 3, 4);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M5', 'E2', 14);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M5', 'C1', 4);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M6', 'Экология', 'Городская программа озеленения и ветрозащитных полос', 'city', 20, 4, 5);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M6', 'E1', 5);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M6', 'E2', 3);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M7', 'Соцсфера', 'Школа + детсад (модульное строительство)', 'district', 24, 3, 6);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M7', 'S1', 16);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M8', 'Соцсфера', 'Центр семейного здоровья / поликлиника', 'district', 20, 3, 7);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M8', 'S2', 14);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M9', 'Соцсфера', 'Дворовые спорт-хабы', 'district', 10, 1, 8);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M9', 'S1', 3);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M9', 'S2', 3);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M9', 'B1', 3);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M10', 'Безопасность', 'Освещение и камеры (расширение Safe City)', 'district', 12, 1, 9);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M10', 'B1', 12);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M10', 'B2', 2);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M11', 'Безопасность', 'Безопасные переходы и школьные зоны', 'district', 10, 1, 10);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M11', 'B2', 12);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M11', 'T1', -2);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M12', 'Сервисы', 'Единая цифровая платформа обращений', 'city', 14, 1, 11);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M12', 'C2', 5);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M13', 'Сервисы', 'Модернизация тепло- и водосетей', 'district', 28, 4, 12);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M13', 'C1', 18);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M13', 'E2', 2);
INSERT INTO measures (id, direction, name, type, cost, lag, order_index) VALUES ('M14', 'Сервисы', 'Аварийные бригады ЖКХ + раннее оповещение', 'city', 16, 1, 13);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M14', 'C1', 5);
INSERT INTO measure_effects (measure_id, indicator_id, effect) VALUES ('M14', 'C2', 2);
INSERT INTO synergies (id, target_measure, order_index) VALUES (1, 'M1', 0);
INSERT INTO synergy_measures (synergy_id, measure_id, position) VALUES (1, 'M1', 0);
INSERT INTO synergy_measures (synergy_id, measure_id, position) VALUES (1, 'M2', 1);
INSERT INTO synergy_effects (synergy_id, indicator_id, effect) VALUES (1, 'T1', 2);
INSERT INTO synergies (id, target_measure, order_index) VALUES (2, 'M10', 1);
INSERT INTO synergy_measures (synergy_id, measure_id, position) VALUES (2, 'M10', 0);
INSERT INTO synergy_measures (synergy_id, measure_id, position) VALUES (2, 'M12', 1);
INSERT INTO synergy_effects (synergy_id, indicator_id, effect) VALUES (2, 'B1', 2);
INSERT INTO synergies (id, target_measure, order_index) VALUES (3, 'M5', 2);
INSERT INTO synergy_measures (synergy_id, measure_id, position) VALUES (3, 'M5', 0);
INSERT INTO synergy_measures (synergy_id, measure_id, position) VALUES (3, 'M6', 1);
INSERT INTO synergy_effects (synergy_id, indicator_id, effect) VALUES (3, 'E2', 2);
INSERT INTO incompatibilities (id, scope, reason, order_index) VALUES (1, 'global', 'либо BRT, либо ЛРТ', 0);
INSERT INTO incompatibility_measures (incompatibility_id, measure_id, position) VALUES (1, 'M1', 0);
INSERT INTO incompatibility_measures (incompatibility_id, measure_id, position) VALUES (1, 'M3', 1);
INSERT INTO incompatibilities (id, scope, reason, order_index) VALUES (2, 'same_district', 'конфликт за участок', 1);
INSERT INTO incompatibility_measures (incompatibility_id, measure_id, position) VALUES (2, 'M4', 0);
INSERT INTO incompatibility_measures (incompatibility_id, measure_id, position) VALUES (2, 'M7', 1);
INSERT INTO incompatibilities (id, scope, reason, order_index) VALUES (3, 'same_district', 'дублирование программы', 2);
INSERT INTO incompatibility_measures (incompatibility_id, measure_id, position) VALUES (3, 'M5', 0);
INSERT INTO incompatibility_measures (incompatibility_id, measure_id, position) VALUES (3, 'M13', 1);
INSERT INTO reference_scenarios (name, data_json, order_index) VALUES ('baseline', '{"decisions":[],"approximate_Score":52.56,"approximate_D_avg":56.86,"D_min":49.18,"N_crit":2}'::jsonb, 0);
INSERT INTO reference_scenarios (name, data_json, order_index) VALUES ('example', '{"decisions":[{"measure_id":"M7","district":"Нура"},{"measure_id":"M8","district":"Нура"},{"measure_id":"M10","district":"Нура"},{"measure_id":"M12"},{"measure_id":"M5","district":"Сарыарка"}],"cost":95,"approximate_Score":56.5}'::jsonb, 1);
INSERT INTO reference_scenarios (name, data_json, order_index) VALUES ('cheapest', '{"measure_ids":["M9","M11","M10","M12","M4"],"cost":61}'::jsonb, 2);
COMMIT;

SET search_path TO "city_simulator";
SELECT 'districts' AS table_name, COUNT(*) FROM districts
UNION ALL SELECT 'indicators', COUNT(*) FROM indicators
UNION ALL SELECT 'measures', COUNT(*) FROM measures
UNION ALL SELECT 'measure_effects', COUNT(*) FROM measure_effects
UNION ALL SELECT 'synergies', COUNT(*) FROM synergies
UNION ALL SELECT 'incompatibilities', COUNT(*) FROM incompatibilities;
